
EEL_SOURCE = nseel-caltab.c nseel-cfunc.c nseel-compiler.c nseel-eval.c nseel-lextab.c nseel-ram.c nseel-yylex.c 

FFT_SOURCE = ../fft.c
CFLAGS = /DWDL_FFT_REALSIZE=8

default: test.exe


test.cpp: eel_*.h ns-eel*.h

$(EEL_SOURCE): ns-eel*.h



test.exe: test.cpp $(EEL_SOURCE) $(FFT_SOURCE)
	cl $(CFLAGS) $**  /link wsock32.lib /out:$@ 
